name       : gcr
version    : 3.40.0
release    : 25
source     :
    - https://download.gnome.org/sources/gcr/3.40/gcr-3.40.0.tar.xz : b9d3645a5fd953a54285cc64d4fc046736463dbd4dcc25caf5c7b59bed3027f5
license    : GPL-3.0-or-later
component  : desktop.gnome.core
summary    : The Gcr package contains libraries used for displaying certificates and accessing key stores. It also provides the viewer for crypto files on the GNOME Desktop.
description: |
    The Gcr package contains libraries used for displaying certificates and accessing key stores. It also provides the viewer for crypto files on the GNOME Desktop.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(p11-kit-1)
    - libgcrypt-devel
    - gnupg
    - vala
setup      : |
    %meson_configure -Dgtk_doc=false
build      : |
    %ninja_build
install    : |
    %ninja_install
