name        : gcr
version     : 3.18.0
release     : 11
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gcr/3.18/gcr-3.18.0.tar.xz : d4d16da5af55148a694055835ccd07ad34daf0ad03bdad929bf7cad15637ce00
license     :
    - GPL-3.0
summary     : The Gcr package contains libraries used for displaying certificates and accessing key stores. It also provides the viewer for crypto files on the GNOME Desktop.
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(p11-kit-1)
    - libgcrypt-devel
    - gnupg
    - vala
description : |
    The Gcr package contains libraries used for displaying certificates and accessing key stores. It also provides the viewer for crypto files on the GNOME Desktop.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
