name       : gcr
version    : 3.20.0
release    : 14
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gcr/3.20/gcr-3.20.0.tar.xz : 90572c626d8a708225560c42b4421f7941315247fa1679d4ef569bde7f4bb379
license    : GPL-3.0
component  : desktop.gnome.core
summary    : The Gcr package contains libraries used for displaying certificates and accessing key stores. It also provides the viewer for crypto files on the GNOME Desktop.
description: |
    The Gcr package contains libraries used for displaying certificates and accessing key stores. It also provides the viewer for crypto files on the GNOME Desktop.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(p11-kit-1)
    - libgcrypt-devel
    - gnupg
    - vala
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
