name       : gcr
version    : 3.41.0
release    : 26
source     :
    - https://download.gnome.org/sources/gcr/3.41/gcr-3.41.0.tar.xz : 0909fc49ea8ad4832d27564ff2fd1dc666696e2a07c73941c48829e60572da01
license    : GPL-3.0-or-later
component  : desktop.gnome.core
summary    : The Gcr package contains libraries used for displaying certificates and accessing key stores. It also provides the viewer for crypto files on the GNOME Desktop.
description: |
    The Gcr package contains libraries used for displaying certificates and accessing key stores. It also provides the viewer for crypto files on the GNOME Desktop.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(p11-kit-1)
    - libgcrypt-devel
    - gnupg
    - openssh
    - vala
setup      : |
    %meson_configure -Dgtk_doc=false
build      : |
    %ninja_build
install    : |
    %ninja_install
