name       : gcr
version    : 3.38.0
release    : 22
source     :
    - https://download.gnome.org/sources/gcr/3.38/gcr-3.38.0.tar.xz : a64cc7b65757fc2cd16de1708d132a16d05cd1f62c6eba436d56fe45d4ba27e1
license    : GPL-3.0-or-later
component  : desktop.gnome.core
summary    : The Gcr package contains libraries used for displaying certificates and accessing key stores. It also provides the viewer for crypto files on the GNOME Desktop.
description: |
    The Gcr package contains libraries used for displaying certificates and accessing key stores. It also provides the viewer for crypto files on the GNOME Desktop.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(p11-kit-1)
    - libgcrypt-devel
    - gnupg
    - vala
setup      : |
    %meson_configure -Dgtk_doc=false
build      : |
    %ninja_build
install    : |
    %ninja_install
